// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package op

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __native_entry__() uintptr

var (
    _subr__masked_vbyte_decode uintptr = __native_entry__() + 160
)

const (
    _stack__masked_vbyte_decode = 48
)

var (
    _ = _subr__masked_vbyte_decode
)

const (
    _ = _stack__masked_vbyte_decode
)
